[2022-03-28 10:13:27,053] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-03-28T16:29:10.852578+00:00 [queued]>
[2022-03-28 10:13:27,058] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-03-28T16:29:10.852578+00:00 [queued]>
[2022-03-28 10:13:27,059] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-28 10:13:27,059] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-28 10:13:27,059] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-28 10:13:27,069] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): also_run_this> on 2022-03-28 16:29:10.852578+00:00
[2022-03-28 10:13:27,071] {standard_task_runner.py:52} INFO - Started process 52709 to run task
[2022-03-28 10:13:27,076] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'manual__2022-03-28T16:29:10.852578+00:00', '--job-id', '10', '--raw', '--subdir', '/home/vengat/big_data/python/venv/aflow_env/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmp_4i76ckd', '--error-file', '/tmp/tmp21i3p17_']
[2022-03-28 10:13:27,077] {standard_task_runner.py:77} INFO - Job 10: Subtask also_run_this
[2022-03-28 10:13:27,149] {logging_mixin.py:109} INFO - Running <TaskInstance: example_bash_operator.also_run_this manual__2022-03-28T16:29:10.852578+00:00 [running]> on host ubuntu
[2022-03-28 10:13:27,183] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-03-28T16:29:10.852578+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-28T16:29:10.852578+00:00
[2022-03-28 10:13:27,184] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-28 10:13:27,185] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=manual__2022-03-28T16:29:10.852578+00:00 | dag_run=<DagRun example_bash_operator @ 2022-03-28 16:29:10.852578+00:00: manual__2022-03-28T16:29:10.852578+00:00, externally triggered: True>"']
[2022-03-28 10:13:27,192] {subprocess.py:85} INFO - Output:
[2022-03-28 10:13:27,194] {subprocess.py:89} INFO - run_id=manual__2022-03-28T16:29:10.852578+00:00 | dag_run=<DagRun example_bash_operator @ 2022-03-28 16:29:10.852578+00:00: manual__2022-03-28T16:29:10.852578+00:00, externally triggered: True>
[2022-03-28 10:13:27,194] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-28 10:13:27,210] {taskinstance.py:1272} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20220328T162910, start_date=20220328T171327, end_date=20220328T171327
[2022-03-28 10:13:27,251] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-28 10:13:27,275] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
